@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <b>x</b>

table(uniterms) {
  primary_key(id): BIGINT
  name: VARCHAR NOT NULL
  expression: VARCHAR NOT NULL
  description: VARCHAR
}

@enduml