@startuml
start
:Użytkownik otwiera aplikację;
:System wyświetla listę istniejących unitermów;
:Użytkownik wybiera "Dodaj Uniterm";
:System wyświetla formularz tworzenia unitermu;
:Użytkownik wprowadza nazwę unitermu i wybiera typ operacji;
:System tworzy nowy uniterm;
:Użytkownik wybiera dodanie elementów do unitermu;
:System wyświetla formularz tworzenia elementu;
:Użytkownik dodaje wyrażenia do elementu;
:System dodaje element do unitermu;
:Użytkownik żąda wizualizacji unitermu;
:System renderuje uniterm na canvasie;
:Użytkownik wybiera transformację unitermu;
:System pokazuje podgląd przekształconego unitermu;
:Użytkownik potwierdza transformację;
:System zapisuje przekształcony uniterm;
stop
@enduml