@startuml
start
:Użytkownik otwiera aplikację;
:System wyświetla listę istniejących wyrażeń;
:Użytkownik wybiera "Dodaj nowy";
:System wyświetla dialog dodawania wyrażenia;
:Użytkownik wprowadza wyrażenie i wybiera separator;
:System zapisuje nowe wyrażenie;
:Użytkownik wybiera wyrażenia do zrównoleglenia poziomego;
:System renderuje wizualizację zrównoleglenia;
:Użytkownik wybiera wyrażenia do sekwencjonowania pionowego;
:System renderuje wizualizację sekwencjonowania;
:Użytkownik klika przycisk "Wizualizacja";
:System wyświetla opcje łączenia operacji;
:Użytkownik wybiera "Zamiana za 1" lub "Zamiana za 2";
:System pokazuje wizualizację połączonej operacji;
stop
@enduml