@startuml
actor Użytkownik
participant "UnitermVisualizationControllerComponent" as UVCC
participant "AddUnitermDialogComponent" as AUDC
participant "UnitermVisualizationComponent" as UVC
participant "UnitermMergeVisualizationComponent" as UMVC
participant "UnitermService" as US
participant "Backend" as BE
participant "Baza Danych" as DB

Użytkownik -> UVCC: Wyświetl stronę aplikacji
UVCC -> US: getUniterms()
US -> BE: HTTP GET /api/uniterms
BE -> DB: Zapytanie o unitermy
DB --> BE: Zwrócenie wyrażeń
BE --> US: Zwrócenie listy wyrażeń
US --> UVCC: Aktualizacja listy wyrażeń

Użytkownik -> UVCC: Kliknięcie "Dodaj nowy"
UVCC -> AUDC: Otwarcie dialogu
Użytkownik -> AUDC: Wprowadzenie wyrażenia
AUDC -> US: saveUniterm(noweWyrażenie)
US -> BE: HTTP POST /api/uniterms
BE -> DB: Zapisanie wyrażenia
DB --> BE: Potwierdzenie zapisu
BE --> US: Zwrócenie zapisanego wyrażenia
US --> UVCC: Odświeżenie listy wyrażeń

Użytkownik -> UVCC: Wybór wyrażeń do zrównoleglenia
UVCC -> UVC: Aktualizacja [uniterms] dla zrównoleglenia
UVC --> UVCC: Wyświetlenie zrównoleglenia

Użytkownik -> UVCC: Wybór wyrażeń do sekwencjonowania
UVCC -> UVC: Aktualizacja [uniterms] dla sekwencjonowania
UVC --> UVCC: Wyświetlenie sekwencjonowania

Użytkownik -> UVCC: Zmiana separatora
UVCC -> UVC: Aktualizacja [separator]
UVC --> UVCC: Odświeżenie wizualizacji

Użytkownik -> UVCC: Kliknięcie "Wizualizacja"
UVCC -> UMVC: Przekazanie wyrażeń równoległych i sekwencyjnych
Użytkownik -> UMVC: Wybór "Zamiana za 1/2"
UMVC -> UMVC: Renderowanie połączonej wizualizacji
UMVC --> UVCC: Wyświetlenie wizualizacji
@enduml