@startuml
actor Uzytkownik

package "Aplikacja webowa (frontend)" {
    (Dodaj wyrażenie)
    (Wyświetl zrównoleglenie poziome)
    (Wyświetl sekwencjonowanie pionowe)
    (Wybierz separator wyrażeń)
    (Wizualizuj połączenie operacji)

    Uzytkownik --> (Dodaj wyrażenie)
    Uzytkownik --> (Wyświetl zrównoleglenie poziome)
    Uzytkownik --> (Wyświetl sekwencjonowanie pionowe)
    Uzytkownik --> (Wybierz separator wyrażeń)
    Uzytkownik --> (Wizualizuj połączenie operacji)
}

package "Backend (Spring Boot REST API)" {
    (Pobierz listę wyrażeń)
    (Zapisz wyrażenie)

    Uzytkownik --> (Pobierz listę wyrażeń)
    Uzytkownik --> (Zapisz wyrażenie)

    database "Baza danych PostgreSQL" as DB
    (Zapisz wyrażenie) --> DB
    (Pobierz listę wyrażeń) --> DB
} 
@enduml