@startuml
package "Frontend" {
  [Komponent App] as AppComp
  [Komponent Listy Unitermów] as ListComp
  [Komponent Edytora Unitermów] as EditComp
  [Komponent Wizualizacji Unitermów] as VisComp
  [Komponent Dialogu Dodawania Unitermu] as AddDialogComp
  [Komponent Dialogu Dodawania Elementu] as ElemDialogComp
  [Serwis Unitermów] as UnitermSvc
  
  AppComp --> ListComp
  ListComp --> EditComp
  EditComp --> VisComp
  ListComp --> AddDialogComp
  EditComp --> ElemDialogComp
  ListComp --> UnitermSvc
  EditComp --> UnitermSvc
}

package "Backend" {
  [Kontroler Unitermów] as UnitermCtrl
  [Serwis Unitermów] as UnitermSvcBE
  [Repozytorium Unitermów] as UnitermRepo
  [Konfiguracja Bezpieczeństwa] as SecConfig
  
  UnitermCtrl --> UnitermSvcBE
  UnitermSvcBE --> UnitermRepo
  UnitermCtrl --> SecConfig
}

UnitermSvc --> UnitermCtrl : HTTP
@enduml